spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ags_cloudtech?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: agscloudtechnologies@gmail.com
    password: lalo dasw wrwy mlyz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: BirthdayEmailApp