# This file is part of the Birthday Greetings App project.
name: birthday-greetings-app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: agscloudtech
          POSTGRES_DB: birthdaygreeting_app
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DB_URL: jdbc:postgresql://localhost:5432/birthdaygreeting_app
      DB_USERNAME: postgres
      DB_PASSWORD: agscloudtech
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean install
      - name: Run tests
        run: mvn test
      # Add after 'Checkout code' step
      - name: Set snapshot version
        run: mvn versions:set -DnewVersion=1.0.${{ github.run_number }}-SNAPSHOT

      # For stable release (add a separate job or workflow triggered by tag)
      - name: Set release version
        run: mvn versions:set -DnewVersion=1.0.${{ github.run_number }}
